### ISSUE TITLE
Bad Performance

### ISSUE THREAD

**Issue by lagoasoft-lucasschmidt** [rotundasoftware/cartero#25]
Hey guys, I am currently having a performance issue, since for each page/parcel, a new browserify instance is created, and all files are processed over again. 

I have a lot of `coffee` and `jade` files that are compiled. Even if I add a cache mecanism, it doesnt work, since the browserify instance changes from parcel to parcel. 

Do u guys have any idea if its easy to implement a browserify instance option in cartero? I did try and for some reason I got no success, but I will still attempt this.

**Comment by dgbeck** [comment]
Hi Lucas,

As of 5.0.0, cartero now uses just one instance of browserify, regardless of the number of entry points, so each asset is only processed once no matter how many times it is required. Running cartero on a lot of entry points is now way, way faster. (Also, cartero will now output a common bundle for the assets that are shared between all entry points! Check it out!)

Hope all is well with you!

**Comment by lucastschmidt** [comment]
@dgbeck great. I actually had to create some tools to handle the huge amount of pages I had to process. (deploys were taking too long) The implementation ended up being so simple, it amazed me. Currently, I ended up simply using plain browserify in a gulp pipeline. I just had to create an algorithm to calculate the entry points, based on views folders, a gulp plugin to map the entry points to a json file, and a middleware to inject the js.

I ended up with 3 small, "independent" pieces of code.

I had huge performance improvements by using plain browserify, compared to the old cartero model. I still had issue with like increasing the amount of pages processed, and I was able to create a common bundle as well with browserify, to improve speed, and it didnt take a lot of work to make it work. 

For now I am only using cartero1 or 2 I think in some old projects, but I will see if I can test the new version.

**Comment by dgbeck** [comment]
Hi Lucas! Sounds like you took a similar approach as we did with cartero v5, using just one browserify instance and factor bundle. sorry we didn't get to that earlier for you! Its damn fast now.. a more than an order of magnitude faster in the case of our app with around 15 entry points. Definitely recommend checking it out when you get the opportunity. Watch mode is super efficient as well. Keep me posted!

**Comment by lucastschmidt** [comment]
Yeah @dgbeck , I am going to try and check it out.

I think I am actually using one instance per page, something along these lines: http://fettblog.eu/gulp-browserify-multiple-bundles/
