### ISSUE TITLE
Cartero 3: Assets.json using absolutePath

### ISSUE THREAD

**Issue by lucastschmidt** [rotundasoftware/cartero#30]
Hey guys, I am having an issue:

our deploy script basically:
- npm install
- grunt
- cartero
- move to another machine (thats the issue, due to absolutePath)
- start

The issue is that the *assets.json* file maps absolutePaths.

In the previous project we used Cartero 2, there it maps only relativePath from the parcelsDir. Eg:

`` "header": "0e77701ef5732d1862fc323ab8a04fe11e782400", `` 

Do you guys have any ideas why this is now the case, or if this is just a configuration issue on my part?

**Comment by dgbeck** [comment]
Lucas! Yes sir you are correct sir!

This behavior was indeed changed. I remember thinking that this could come back to bite us at the time and apparently the time has come. If memory services I think we'll want to add another option called 'rootDir' that if supplied, is used as the base of all the paths that are currently absolute.

What is your timeline?

**Comment by lucastschmidt** [comment]
Hey, thanks for the quick answer.

Not really a huge issue currently, since we are just in testing phase, and I can actually use the hook I did for development: it processes the page when user opens the page for the first time, so, it works currently with that hook. 

If necessary I can try to do something about it as well, just point me at the right direction.

**Comment by dgbeck** [comment]
Ok, I will put this on my list of pending items, and shoot for getting it done in February.

**Comment by lucastschmidt** [comment]
@dgbeck sure, no problem.

**Comment by dgbeck** [comment]
Hi @lucastschmidt! Hope all is well with you!

Just was able to implement this feature. Sorry about the delay. The option was just added in v4.2.0 and is called `appRootDir`. Feel free to take it for a whirl let me know if it doesn't resolve this issue.

**Comment by lucastschmidt** [comment]
Thx @dgbeck, no issues.
