### ISSUE TITLE
How to reuse package assets in another package?

### ISSUE THREAD

**Issue by mediafreakch** [rotundasoftware/cartero#31]
The following scenario:

- core-package
  - variables.less

- reuse-package
  - style.less

How can I re-use the LESS variables defined in variables.less from the core-package in the style.less file inside reuse-package, then transform the style.less and dump it to public/assets?

**Comment by dgbeck** [comment]
Hi @mediafreakch ! At first glance it seems as though how to include `variables.less` from `style.less` is just a matter of setting up the proper less `@import` directive.

Maybe I am not understanding the question / problem though?

**Comment by mediafreakch** [comment]
Seems like I am messing up something. I expected to be able to define a core-package containing some global parameters for other packages to consume. In a depending package I wanted to declare a dependency to that core-package and re-use parameters defined there.

`@import "../core-package/variables.less";` doesn't seem quite right, is it? After all I think the problem doesn't have to do anything with cartero at all in my use-case. I have to give it some more thoughts. Thanks anyway for the quick reply!

**Comment by dgbeck** [comment]
Yeah I think what you are looking to do can be done and it involves the `@import` directive. In the sass word the way we do this is to set the import paths, so that you can just do `@import "variables.less";` Good luck!
