### ISSUE TITLE
Error running cartero programmatically

### ISSUE THREAD

**Issue by mediafreakch** [rotundasoftware/cartero#32]
Hi,

I'm trying to run cartero from a node script like that:
```
cartero = require('cartero');

res = cartero('./', './dist/', {
    assetTypes: ['files']
});
```
I'm getting the following error:

```
Error: Cannot find module './build/Release/fse' from '{userpath masked}/node_modules/cartero/node_modules/watchify/node_modules/chokidar/node_modules/fsevents'
```

**Comment by dgbeck** [comment]
Hi @mediafreakch ! At first glance looks like some sort of versioning issue. I'm not seeing a `./build/Release/fse' module in the [fsevents repo](https://github.com/strongloop/fsevents).

1. I image you get this same error when running cartero from the command line yes?
2. Can you check and post what version of cartero, watchify, chokidar, and fsevents are installed?

**Comment by mediafreakch** [comment]
Hi,

1. Yes, same error on command line
2a. Cartero: 4.0.0
2b. Watchify: 3.2.0
2c. Chokidar: 1.0.1
2d. Fsevents: 0.3.5

So I assume the issue is not residing inside cartero itself. Any idea how to work around that? It makes cartero unusable for me right now.

**Comment by mediafreakch** [comment]
In case you wondered: The issue occurs both on Mac OSX and Windows

**Comment by dgbeck** [comment]
HI @mediafreakch ,

Can you try `npm rebuild` in your project directory?

Also, what version of node are you running?

**Comment by mediafreakch** [comment]
Hi,

`npm rebuild` didn't have any effect. I had some old versions of npm (`1.4.13`) and node (`0.10.28`) installed. 

I updated them so that node now is `v0.12.2` and npm is `2.7.4`. I re-installed the cartero package, run `npm rebuild` again but the issue remains.

**Comment by dgbeck** [comment]
Hi Edi, can you try bumping to cartero v4.0.2, just pushed. That version bumps the version of watchify, parcelify, and glob watcher, all which seemed to have some incompatibles with node v0.12.2 due to a change in fsevents, or something.

You might need to run `npm rebuild` again as well.

Let me know how that goes!

**Comment by mediafreakch** [comment]
Hi,

Unfortunately that doesn't solve the problem (you didn't publish on npm, so I just took the sources from Github and run npm install inside the cartero directory). I verified that the latest versions of all the packages are installed.

Maybe we are missing something. That's the full error message:

```
ERR! Error: Cannot find module './build/Release/fse' from '/Users/.../Sites/StaticServer/node_modules/cartero/node_modules/watchify/node_modules/chokidar/node_modules/fsevents'
ERR!     at /Users/.../Sites/StaticServer/node_modules/cartero/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
ERR!     at load (/Users/.../Sites/StaticServer/node_modules/cartero/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
ERR!     at onex (/Users/.../Sites/StaticServer/node_modules/cartero/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
ERR!     at /Users/.../Sites/StaticServer/node_modules/cartero/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
ERR!     at FSReqWrap.oncomplete (fs.js:95:15)
ERR!  [Error: Cannot find module './build/Release/fse' from '/Users/.../Sites/StaticServer/node_modules/cartero/node_modules/watchify/node_modules/chokidar/node_modules/fsevents']
```

**Comment by dgbeck** [comment]
hm. can you post the output of `npm rebuild`? (4.0.2 is now published, sorry  bout that.)

**Comment by mediafreakch** [comment]
Output is insanely big. Guess the interesting part is this:

```
> fsevents@0.3.5 install /Users/.../Sites/StaticServer/node_modules/cartero/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
```

**Comment by dgbeck** [comment]
Hi @mediafreakch ,

Taking another look at this, it might have to do with supplying the working directory as the parcels directory. The above code snippet passing `'./'` as the first argument seems like it could cause problems. I think what is happening is that catero is being run on the code snippet itself, and as a result browserify is being run on cartero.

Try running cartero on a directory that is not the directory that contains the snippet. For example

```
cartero = require('cartero');

res = cartero('./views', './dist/', {
    assetTypes: ['files']
} );
```

Or you can be more explicit by supplying an array of js entry points

```
cartero = require('cartero');

res = cartero(['./index.js'], './dist/', {
    assetTypes: ['files']
} );
```

Better luck?

Also, to confirm this is not a versioning issue, you can checkout a clean copy of cartero, run npm install, and then run the cartero tests.

```
$ git clone https://github.com/rotundasoftware/cartero.git
$ cd cartero
$ npm install
$ npm test
```

All tests should pass.

**Comment by mediafreakch** [comment]
Following your suggestions solved my problem. Also, all the tests run without hassle.

However I'd like to point out that the problem was due to an `index.js` inside the working directory, which contained the call to cartero as shown above. Changing the name of that script to something else and creating an empty `index.js` solved the problem as well. I now can run cartero from the working directory.

Thanks a lot for your time!
