### ISSUE TITLE
Valid assetTypes

### ISSUE THREAD

**Issue by mediafreakch** [rotundasoftware/cartero#34]
Hello,

The docs state that using cartero API you can specify the keys in package.json that enumerate assets.

> `assetTypes` (default: [ 'style', 'image' ]) -The keys in package.json files that enumerate assets that should be copied to the cartero output directory

To verify that it should work, I modified `Example 3` of the tests contained in the cartero repo to this:

```
// cartero/test/example3/views/package.json
{
	"name" : "common-js",
	"main" : "common.js",
	"style" : "*.css",
	"random" : ["*.png"]
}
```

```
// cartero/test/test.js - line 119
var c = cartero( viewDirPath, outputDirPath, { assetTypes: ["random", "style"]} );
```

The test does not pass: `not ok 12 robot.png in common package`

Is there a limited set of supported keys or is it a bug?

**Comment by dgbeck** [comment]
Hi again @mediafreakch. Yes, this was in fact a bug. [Fixed](https://github.com/rotundasoftware/cartero/commit/33aac31793de8b6cdbcaf08bbea8621b2a0fab9b) in v4.0.3, just published. Thanks!
