### ISSUE TITLE
How to use different transforms on different file types?

### ISSUE THREAD

**Issue by ericsoco** [rotundasoftware/cartero#41]
I need to apply `reactify` to my `.jsx` files and `sass-css-stream` to my `.scss` files. How can I configure this a) as an `appTransform` and b) within `package.json` files in each package directory?

**Comment by dgbeck** [comment]
Hi @ericsoco !

Which transform is applied to which file is determined by file extension, the tests being hardcoded into each of those two transform modules. There is nothing special that needs to be done beyond what is described in the cartero docs. Are you experiencing a problem? If so, can you provide more specifics?

**Comment by ericsoco** [comment]
Hm, I guess I'm primarily confused about how to make both those transforms happen in one command. Or is that not as designed? Would it make more sense to run those two tasks in parallel?

**Comment by dgbeck** [comment]
Hi @ericsoco ,

I might not be understanding the question correctly, but for package transform, you just include an entry in package.json

```
"transforms" : [ "sass-css-stream", "reactify" ],
```

For `appTransforms`, pretty much the same thing

```
c = cartero( entryPoints, outputDir, {
   appTransforms : [ "sass-css-stream", "reactify" ],
   appTransformDirs : [ ... ]
} )
```

**Comment by ericsoco** [comment]
Ah right. And the transforms determine which files (by extension) they will operate on. Got it, thanks!
